// SPDX-License-Identifier: MIT
/**
 * Perxona Connect Kit -- Presenter API contract
 *
 * AUTO-GENERATED by Perxona Connect Kit codegen. DO NOT EDIT.
 * Generated from the Perxona widget presenter interface.
 *
 * <sv-presenter> implements IPresentationWidget. Use this file for IDE
 * autocomplete and JSDoc when calling presenter methods from your integration.
 *
 * This file also includes the supporting data types and the <sv-presenter>
 * event types (PresentationWidgetEvent and friends) for use with addEventListener.
 */
// -- type/AssetQuality.ts ----------------------------------------------------

export declare enum AssetQuality {
    High = "lod0",
    Medium = "lod1",
    Low = "lod2"
}

// -- type/AvatarConfig.ts ----------------------------------------------------

export type MotionSet = Record<MotionState, MotionAsset[]>;
export type AvatarConfig = {
    id: string;
    assetUrls: Record<AssetQuality, string>;
    motions: MotionSet;
    defaultFacial: MotionAsset[];
    lipsyncMode: LipSyncMode;
    lipsyncConfig: Record<string, LipSyncConfig>;
};

// -- type/CameraConfig.ts ----------------------------------------------------

export declare enum CameraAngle {
    Fullbody = "fullbody",// Framing.HeadToToe
    Halfbody = "halfbody"
}
export type CameraFOV = {
    distance?: number;
    vertical?: number;
    horizontal: number;
};
export declare enum ScreenFitStrategy {
    FitWidth = "fit-width",
    FitHeight = "fit-height",
    Adaptive = "adaptive"
}

// -- type/CustomEvents.ts ----------------------------------------------------

export declare enum PresentationWidgetEvent {
    PRESENTER_STATUS = "PRESENTER_STATUS",
    ASSET_LOADING_PROGRESS = "ASSET_LOADING_PROGRESS",
    AUDIO_PLAYBACK_STATE = "AUDIO_PLAYBACK_STATE",
    SPEECH_TOKEN_EXPIRED = "SPEECH_TOKEN_EXPIRED",
    PERFORMANCE_START = "PERFORMANCE_START",
    PERFORMANCE_END = "PERFORMANCE_END",
    ALL_PERFORMANCE_FINISHED = "ALL_PERFORMANCE_FINISHED",
    PERFORMANCE_STATE = "PERFORMANCE_STATE",
    PLAYING_SPEECH_TEXT = "PLAYING_SPEECH_TEXT"
}
export declare enum PresenterStatus {
    Uninitialized = "Uninitialized",
    Initializing = "Initializing",
    Ready = "Ready"
}
export declare enum AssetType {
    Avatar = "Avatar",
    Motion = "Motion",
    Scene = "Scene"
}
export declare enum PerformanceState {
    Idle = "Idle",
    Listening = "Listening",
    Thinking = "Thinking",
    Talking = "Talking"
}
export interface PresentationEvent {
    eventType: PresentationWidgetEvent;
}
export declare class PresenterStatusEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PRESENTER_STATUS;
    readonly status: PresenterStatus;
    constructor(status: PresenterStatus);
}
export declare class AssetLoadingProgressEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.ASSET_LOADING_PROGRESS;
    readonly assetType: AssetType;
    readonly progress: number;
    constructor(assetType: AssetType, progress: number);
}
export declare class AudioPlaybackStateEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.AUDIO_PLAYBACK_STATE;
    readonly state: AudioContextState;
    constructor(state: AudioContextState);
}
export declare class SpeechTokenExpiredEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.SPEECH_TOKEN_EXPIRED;
}
export declare class PerformanceStartEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_START;
}
export declare class PerformanceEndEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_END;
}
export declare class AllPerformanceFinishedEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.ALL_PERFORMANCE_FINISHED;
}
export declare class PerformanceStateEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PERFORMANCE_STATE;
    readonly state: PerformanceState;
    constructor(state: PerformanceState);
}
export declare class PlayingSpeechTextEvent implements PresentationEvent {
    readonly eventType = PresentationWidgetEvent.PLAYING_SPEECH_TEXT;
    readonly text: string;
    constructor(text: string);
}

// -- type/LipSyncConfig.ts ---------------------------------------------------

export declare enum LipSyncMode {
    XRLipSync = "xrlipsync",
    WLipSync = "wlipsync"
}
export type LipSyncConfig = {
    configUrl: string;
    profileUrl: string;
};
export declare enum BlendshapeProcessorType {
    Raw = "raw",
    Smoothed = "smoothed"
}

// -- type/MotionAsset.ts -----------------------------------------------------

export declare enum MotionState {
    Idle = "idle",
    Talking = "talking",
    Listening = "listening",
    Loading = "loading",
    Error = "error"
}
export declare enum MotionType {
    Body = "body",
    Face = "face"
}
export type MotionAsset = {
    id: string;
    type: MotionType;
    assetUrl: string;
};

// -- type/Performance.ts -----------------------------------------------------

export type Performance = {
    /**
     * All the preemptive motion assets that will be used in this performance.
     * These motions should be preloaded before playing the performance to ensure smooth playback.
     */
    motions: MotionAsset[];
    /**
     * The text content of the performance
     */
    message: string;
    /**
     * The SSML string for the performance, which will be converted to speech.
     */
    ssml: string;
    /**
     * The name of the voice to be used for speech synthesis and switching lip-sync configuration in this performance.
     */
    voiceName: string;
};
export type PerformanceOptions = {
    strategy: PlayStrategy;
};
export declare enum PlayStrategy {
    /**
     * Default strategy which will enqueue the performance to the end of the performance queue and play sequentially.
     */
    EnqueueToPlay = "enqueueToPlay",
    /**
     * This strategy will interrupt the current performance and clear the performance queue, then play the new performance immediately.
     */
    InterruptToPlay = "interruptToPlay"
}
export declare const DEFAULT_PERFORMANCE_OPTIONS: PerformanceOptions;

// -- type/PerformanceClip.ts -------------------------------------------------

export type Motion = {
    bodyMotionId: string;
    faceMotionId?: string;
    /**
     * The priority of the motion, ranging from 0 to 100.
     * 0 means always preemptible, 100 means never preemptible.
     */
    priority: number;
    /**
     * Time offset from the PlayMotion trigger when the motion starts.
     * @unit milliseconds
     */
    startAtMS: number;
    /**
     * Time offset from the PlayMotion trigger when the motion ends.
     * If `undefined`, the motion will play until it naturally finishes.
     * @unit milliseconds
     */
    endAtMS?: number;
};
export declare enum SilencePurpose {
    /**
     * Silence used to pace the speech segments to improve naturalness, e.g. 11labs inter-segment gaps
     */
    Pacing = "pacing",
    /**
     * Silence used to simulate agent thinking, e.g. spacer delay
     */
    Thinking = "thinking"
}
export type EndingSilence = {
    purpose: SilencePurpose;
    /**
     * Duration of the silence in milliseconds.
     * After this silence, the next performance clip will start.
     * @unit milliseconds
     */
    durationMs: number;
};
export type PerformanceClip = {
    id: string;
    speechText: string;
    speechData: ArrayBuffer;
    audioData?: AudioBuffer;
    voiceName: string;
    blendshapeProcessorType: BlendshapeProcessorType;
    motions: Motion[];
    endingSilence?: EndingSilence;
};

// -- type/PresentationError.ts -----------------------------------------------

export declare enum PresentationResultCode {
    OK = "0",
    COMPONENT_UNMOUNTED = "100",
    PRESENTER_NOT_READY = "101",
    AUDIO_CONTEXT_UNAVAILABLE = "200"
}
export declare class PresentationResult {
    readonly success: boolean;
    readonly code: PresentationResultCode;
    readonly message?: string | undefined;
    private constructor();
    static ok(): PresentationResult;
    static error(code: PresentationResultCode, message: string): PresentationResult;
    static componentUnmounted(): PresentationResult;
    static presenterNotReady(currentStatus: PresenterStatus): PresentationResult;
}

// -- type/SceneConfig.ts -----------------------------------------------------

export type SceneConfig = {
    id: string;
    assetUrls: Record<AssetQuality, string>;
};

// -- IPresentationWidget.ts --------------------------------------------------

/**
 * Interface for the Presentation Widget.
 *
 * **Performance State Hierarchy:**
 * Avatar animations follow a strict priority hierarchy to handle concurrent state requests:
 * 1. **Custom** (Highest) - Specific motions embedded via `playPerformance`.
 * 2. **Talking** - Standard speaking animation active during `playPerformance`.
 * 3. **Thinking** - Triggered by `setThinking(true)`.
 * 4. **Listening** - Triggered by `setListening(true)`.
 * 5. **Idle** (Lowest) - The default state when no other states are active.
 *
 * Higher-priority states always visually override lower-priority ones. For instance, if both
 * `setListening(true)` and `setThinking(true)` are called, the avatar will perform Thinking.
 * If `setThinking(false)` is subsequently called, the avatar will fall back to Listening.
 */
export interface IPresentationWidget {
    /**
     * Initializes the presentation widget with the specified avatar, scene configuration, and speech token.
     *
     * @param avatar The configuration for initializing an avatar
     * @param scene The configuration for initializing a scene
     * @param speechToken The Azure Speech Service token used for initializing speech synthesizer
     */
    initialize(avatar: AvatarConfig, scene: SceneConfig, speechToken: string): void;
    /**
     * Plays a performance which includes speech and motions with specific play strategy.
     *
     * Note: This activates the top-priority states (**Custom** / **Talking**). Any active lower-priority
     * states (Thinking, Listening) will be visually overridden and hidden until the performance completes
     * or is interrupted.
     *
     * @param performance The data to transform into speech and motions and be played
     * @param options The options to determine the play strategy of this performance, if not provided, it will use the default strategy (enqueue to play).
     * @returns A PresentationResult indicating the success or failure of the play request, along with error code and message if applicable.
     */
    playPerformance(performance: Performance, options?: PerformanceOptions): PresentationResult;
    /**
     * Interrupts the current performance and clear the performance queue
     *
     * Note: This clears the Custom and Talking states, immediately revealing any underlying active
     * states (like Thinking or Listening) or falling back to Idle.
     */
    interruptPerformance(): void;
    /**
     * Set the avatar to be in listening state, which will trigger the corresponding motions.
     *
     * Note: The listening motion will only be visible if no higher-priority states (Custom, Talking, or Thinking) are active.
     *
     * @param isListening A boolean indicating whether the avatar should be in listening state.
     */
    setListening(isListening: boolean): void;
    /**
     * Set the avatar to be in thinking state, which will trigger the corresponding motions.
     *
     * Note: The thinking motion will override the Listening, Idle state, but will remain hidden if a performance
     * (Custom or Talking) is currently playing.
     *
     * @param isThinking A boolean indicating whether the avatar should be in thinking state.
     */
    setThinking(isThinking: boolean): void;
    /**
     * Mute or unmute the audio output of the speech performance.
     *
     * @param muted A boolean indicating whether the audio should be muted.
     */
    muteAudio(muted: boolean): void;
    /**
     * Resumes the AudioContext to comply with browser autoplay policies.
     *
     * Browsers block autoplay audio until the user interacts with the page.
     * Call this method from a direct user interaction callback (e.g., a button click)
     * to ensure speech audio can be played.
     *
     * @returns A Promise that resolves when the context has resumed. The promise is rejected if the context has already been closed.
     */
    resumeAudioPlayback(): Promise<void>;
    /**
     * Updates the camera angle of the viewer.
     *
     * @param cameraAngle The desired camera angle, either 'fullbody' or 'halfbody'.
     * This will adjust the view to show either the full body or just the upper half of the avatar.
     */
    updateCameraAngle(cameraAngle: CameraAngle): void;
    /**
     * Adjust the camera's field of view (FOV) settings.
     *
     * @param fov The camera field of view settings, including distance, vertical FOV, and horizontal FOV.
     */
    updateCameraFOV(fov: CameraFOV): void;
    /**
     * Used to refresh the speech synthesis token when it expired or about to expire, to ensure uninterrupted speech performance.
     *
     * @param token The token to synthesize speech.
     */
    refreshSpeechToken(token: string): void;
}
